### ISSUE TITLE
Missing headers

### ISSUE THREAD

**Issue by gbxl** [bytewitchcraft/apollo-absinthe-upload-link#3]
Hey,

I set up my Apollo client like so:

```
import ApolloClient from 'apollo-client'
import { setContext } from 'apollo-link-context'
import { concat } from 'apollo-link'
import { InMemoryCache } from 'apollo-cache-inmemory'
import { createLink } from "apollo-absinthe-upload-link"

const httpLink = createLink({ uri: `${process.env.config.API_BASE_URL}/v2` })

const authLink = setContext(() => {
  let token = null
  // get the authentication token from local storage if it exists
  if (localStorage.getItem('auth')) {
    token = JSON.parse(localStorage.getItem('auth')).auth.token
  }
  // return the headers to the context so httpLink can read them
  return {
    headers: {
      'x-spree-token': token ? `${token}` : "",
    }
  }
})

const client = new ApolloClient({
  link: authLink.concat(httpLink),
  cache: new InMemoryCache(),
})
```

But in my query there is no `x-spree-token` header.
If I set it up with a regular Apollo HttpLink this works fine (except for the whole file upload part, obviously :P)

**Comment by dmarkow** [comment]
@gbxl I ran into this problem as well. I ended up using [@novistore/apollo-upload-client](https://www.npmjs.com/package/@novistore/apollo-upload-client) which is a modified version of apollo-upload-client, which will forward any headers in the context with the request. Unfortunately they haven't actually published the source code of their branch so you have to dig into the npm package to see what it's doing.

@ihorkatkov See https://github.com/jaydenseric/apollo-upload-client/blob/master/src/index.mjs for how apollo-upload-client handles it. They pull in the context headers as well as any headers sent to `createUploadLink` and pass them along with the request. They're also using `fetch` instead of a dependency on rxjs which makes it a little more lightweight.

**Comment by ihorkatkov** [comment]
@dmarkow  @gbxl added the fix in #4  Soon will be published. I tested it with @gbxl's code example and it works. Don't forget to allow this header in Corsica configuration

**Comment by ihorkatkov** [comment]
It will be cool if we add support for credentials and link headers too. So contributing is welcome :)

**Comment by gbxl** [comment]
Eager to see it released so I can try out the new package 👍

**Comment by ihorkatkov** [comment]
@gbxl Published 👍  I'm closing this issue. If there will be any questions please write it here.
