### ISSUE TITLE
Release with credentials

### ISSUE THREAD

**Issue by Eein** [bytewitchcraft/apollo-absinthe-upload-link#42]
Just letting you guys know I was smashing my head into the credentials issue because 1.5.0 on NPM does not include the credentials changes last year. It would be nice to see a new version on NPM that includes this.

Just wanted to bring awareness in case anyone else gets stuck on this as well.

Thanks for the awesome package!

Edit:
Note: I just added 
```
"apollo-absinthe-upload-link": "git+https://github.com/bytewitchcraft/apollo-absinthe-upload-link.git#6468dc396bc0cd48b611950963ed90c55c506472",
```
to depedencies and it works fine.

**Comment by vadimshvetsov** [comment]
@ihorkatkov could you please release package or give access to someone? I'm ready to publish releases if you have no time for it.

@Eein Very strange that it works for you because this commit has no `lib` folder, you can check in `node_modules`.

At now I've compiled the last commit on my own and add compiled files to a fork
```
"apollo-absinthe-upload-link": "github:vadimshvetsov/apollo-absinthe-upload-link",
```

**Comment by ihorkatkov** [comment]
Hey guys. Sorry for the delay, published the updated version to the npm
